import type { NextPage } from "next";
import Head from "next/head";
import { CircularGauge } from "../components/circular-gauge/circular-gauge";
import { CodeExercises } from "../components/code-exercises/code-exercises";
import { Playground } from "../components/playground/playground";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>React Component Library</h1>

				<Playground component={CodeExercises} componentProps={{}} />
				{/* <Playground component={CircularGauge} componentProps={{ value: 51 }} /> */}
			</main>
		</div>
	);
};

export default Home;
